### PR TITLE
IWYU: add string for std::string

### PR DESCRIPTION
**Pull request by stha09**

### CODE REVIEW

**Comment by bjacob** [comment]
thanks!

**Comment by jdapena** [comment]
What is pending to land this?

**Comment by bjacob** [comment]
just someone with merge rights needs to merge this.  @talumbau ?

**Comment by talumbau** [comment]
Oh, thanks for tagging me, @bjacob. Will do that now. Sorry for the (very long) delay!

**Comment by talumbau** [comment]
Hmm.. unfortunately something did not go right with the copybara machinery to bring this in. I'll have to investigate.

**Comment by KexyBiscuit** [comment]
Hi, when will this change get into Chromium?

**Pull request merged**
