### PR TITLE
Add basic gitignore

### PR DESCRIPTION
**Pull request by GMNGeoffrey**

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
@bjacob PTAL (I can't formally request a review because I'm not a collaborator)

**Comment by bjacob** [comment]
Thanks!! looking into the collaborators issue now..

**Comment by bjacob** [comment]
Is gitignore ignored by copybara (so can i merge here ?)

**Comment by GMNGeoffrey** [comment]
Only if you configured it to be, which you have not :-)

**Pull request merged**
