### PR TITLE
Fix #68: Missing clear of q7 leading to wrong computations

### LINKED ISSUE #68: Broken computation when running under nodejs on armv7
Fuller investigation has been documented on https://github.com/tensorflow/tensorflow/issues/39509.

It looks like `q7` was removed from the clearage in https://github.com/tensorflow/tensorflow/commit/2359c4e45e1226e4a9d4072c2b7753b5ae731f44#diff-ca44636122d5fd4fe9600903ebf461b9L665.

I honestly don't know why it would expose this behavior only under NodeJS and only on ARMv7 platform, but re-instating `q7` as in https://github.com/tensorflow/tensorflow/pull/39951 fixes the issue.

Since `q7` is cleared at other places `q6-q15` are cleared, and since there's no specific comment regarding the removal of `q7` at this place, is it possible it's just a slight typo and I have been lucky in finding it?

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by bjacob** [comment]
Great catch. Thanks a bunch for this fix.

**Comment by bjacob** [comment]
@talumbau

**Comment by bjacob** [comment]
(oops, i merged on the github side first, pulling into google now, hope it won't get confused.)

**Comment by lissyx** [comment]
Also, should that be backported to tensorflow 2.2?

**Comment by bjacob** [comment]
Good point regarding backporting. I filed a google internal tensorflow issue (b/157660965) to track this.

**Comment by bjacob** [comment]
Let me know as a useful data point if you specifically need this to be backported to tf 2.2 or any specific branch.

**Comment by bjacob** [comment]
Got a reply from TF maintainers: "The 2.2 branch was cut on 3/2, and unless this is a security issue it's probably too late to cherry-pick anything for that release. We have an upcoming branch on June 6 for 2.3, so this may just have to wait."

**Comment by lissyx** [comment]
Thanks, we don't have a specific need since we y'a e a fork of tensorflow for building the lib.

**Pull request merged**
