### PR TITLE
Update block_map.h to fix build error with GCC-11.1.0

### PR DESCRIPTION
**Pull request by samcom12**

### CODE REVIEW

**Comment by talumbau** [comment]
Thanks for the report about compilation errors on gcc 11.1. Can you explain the inclusion of `<stdexcept>`? I don't believe we use any symbols from t stdexcept in Ruy.

**Comment by samcom12** [comment]
@talumbau  You are right. We can ignore adding  `<stdexcept>`

**Comment by talumbau** [comment]
Actually, are you sure the issue persists with current main? We recently merged https://github.com/google/ruy/pull/253/files which includes <limits> in block_map.cc, which is appropriate AFAICT. Please sync to latest and let me know if this issue persists (also include compilation line in that case). Thanks!

**Comment by samcom12** [comment]
Actually, I'm using it for building Tensorflow with SPACK. and Tensrflow confirmation picks up an older archive. I Will test with the `master `and let you know by doing internal changes into the build.

**Comment by talumbau** [comment]
I see. Are you referring to this project?

https://github.com/spack/spack

**Comment by samcom12** [comment]
> I see. Are you referring to this project?
> 
> https://github.com/spack/spack

Yes..

**Pull request closed without merging**
