### PR TITLE
limits include added

### PR DESCRIPTION
**Pull request by nibeh**
Added <limits> std include to fix build errors, e.g. https://github.com/tensorflow/tensorflow/issues/35626

### CODE REVIEW

**Review by talumbau — APPROVED** [review]
LGTM. We are using `std::numeric_limits` here so make sense. Thanks!

**Comment by talumbau** [comment]
This looks like a reasonable change, but just curious: it looks like https://github.com/tensorflow/tensorflow/issues/35626 doesn't error out on lacking the include of `<limits>`. Do you have reason to believe that this change would fix the build error reported there?

**Comment by nibeh** [comment]
> This looks like a reasonable change, but just curious: it looks like [tensorflow/tensorflow#35626](https://github.com/tensorflow/tensorflow/issues/35626) doesn't error out on lacking the include of `<limits>`. Do you have reason to believe that this change would fix the build error reported there?

You are right. I linked the wrong issue. Meanwhile I saw, this is a duplicate of https://github.com/google/ruy/pull/253

**Comment by talumbau** [comment]
Ah, I also missed #253 I approved it and started the merge.

**Comment by bjacob** [comment]
Hi @talumbau , thanks for monitoring this - did you mean to merge this PR or not? If so, please add the 'ready to pull' tag to this PR, which will initiate the import.

**Comment by bjacob** [comment]
Thanks @talumbau for initiating the import! You should have received a gerrit email notification. You need to reply with a +2 on the gerrit review to allow the import to proceed into a google 'CL'.

**Comment by talumbau** [comment]
Yes right. I recall this is the standard workflow. I just checked now and can confirm I didn't get the usual email. Also, when I look at the Gerrit server for open changes, I don't see one for Ruy. The most recent Gerrit changes that I see for a github_pr_to_piper change is from February. I wonder if the mechanism stopped working?

**Comment by bjacob** [comment]
Let me remove the ready-to-pull tag, re-add it, and monitor copybara jobs...

**Comment by bjacob** [comment]
Actually here is what happened:

According to `copybara service` the import job did run but exited with `NO_OP`:

```
|2021-06-16T12:14:00 |github_pr_to_piper |google/ruy_267__e41a600a-ca8b-48f1-874d-623e8643ba6d |FINISHED |45          |NO_OP               |
```

Indeed, the `#include <limits>` is already present in google's internal repo.

**Comment by bjacob** [comment]
And according to internal `blame` tools, it was added by you, one month ago, in this change:

```
Internally reflect Github PR #253
```

**Comment by talumbau** [comment]
Ah, yes, this PR was a duplicate of that one. Thanks for handling!

**Pull request closed without merging**
