### PR TITLE
Add git submodules: googletest and cpuinfo

### PR DESCRIPTION
**Pull request by bjacob**

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Just watch out that Copybara actually adds these properly when you import and submit

**Comment by bjacob** [comment]
> Just watch out that Copybara actually adds these properly when you import and submit

Sorry, can you elaborate? I dont understand what Copybara should be doing about this: since git submodules are a git-only concept, I was expecting Copybara to NOT have anything to do about this.

**Comment by GMNGeoffrey** [comment]
Unless you're explicitly excluding `.gitmodules` and `third_party/` from consideration in Copybara (which, I just double-checked your config, you're not) it will try to manage these directories, which means you need to import this through the regular Copybara flow. You could exclude these (in particular you should exclude third_party/), but then if something changes submodules and something else you rely on Copybara integrating the change properly (which it frequently doesn't). I can chat with you about what to do tomorrow.

**Comment by bjacob** [comment]
Thanks so much for catching this! I'll take your offer of a chat on this tomorrow, ping me when you're available.

**Comment by bjacob** [comment]
To prepare more material ahead of tomorrow's conversation, here's a draft for the next PR in this sequence, point the Bazel WORKSPACE to the submodules. It works as far as `bazel build` is concerned...
https://github.com/google/ruy/pull/236

**Comment by GMNGeoffrey** [comment]
So I screwed up reviewing this. Your submodules are at the root of your repo. You should probably put them underneath `third_party/`. Otherwise your copybara excludes also won't work

**Comment by bjacob** [comment]
Oops, sorry my bad. https://github.com/google/ruy/pull/240

**Pull request merged**
