### PR TITLE
move example.cc into one directory

### PR DESCRIPTION
**Pull request by Leslie-Fang**
move the examples into one directory.

### CODE REVIEW

**Comment by bjacob** [comment]
Thanks!

**Comment by bjacob** [comment]
Had to fix it up to make the above 'feedback/copybara' CI happy - was just missing a package license declaration.

**Comment by Leslie-Fang** [comment]
Should we add some license declaration in some files of this PR?

**Comment by bjacob** [comment]
I'm taking care of it - then I ran into an internal issue in our tool (copybara) exporting code back to github - will be fixed here very soon.

**Pull request closed without merging**
