### PR TITLE
cpuinfo

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Right now it uses clog as fetched from a separate `http_archive` and
creates it as a separate Bazel repo, which is pretty weird. This can
all be one Bazel repository.

This build file is identical to the one we have in IREE
(https://github.com/google/iree/blob/main/build_tools/third_party/cpuinfo/BUILD.overlay added in https://github.com/google/iree/pull/4450),
which I created by merging together the build files used in ruy.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
@bjacob PTAL

**Comment by bjacob** [comment]
thanks!! i had no idea that cpuinfo had its own copy of clog/ and I was puzzled how IREE could build cpuinfo without clog!

**Comment by GMNGeoffrey** [comment]
Since this is all files you exclude with Copybara you have to merge it directly :-)

**Comment by bjacob** [comment]
aah :-)

**Pull request merged**
